name: majan_road
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.5.0-266.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  collection: ^1.18.0
  # flutter_map: ^7.0.1
  flutter_map_marker_popup: ^6.1.2
  http_parser: ^4.0.2
  js: ^0.6.7
  material_color_utilities: ^0.11.1
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  animated_text_kit: ^4.2.2
  animations: ^2.0.11
  smooth_page_indicator: ^1.1.0
  icons_plus: ^5.0.0
  salomon_bottom_bar: ^3.3.2
  http: ^1.2.0
  flutter_map: ^6.2.1
  flutter_map_marker_cluster: ^1.3.5
  geolocator: ^12.0.0
  location: ^6.0.2
  # mapbox_gl: ^0.16.0
  # mapbox_search: ^4.2.2s
  # google_maps_flutter: ^2.5.3
  url_launcher: ^6.3.0
  latlng: ^2.0.7
  latlong2: ^0.9.1
  image_picker: ^1.0.8
  get: ^4.6.6
  top_snackbar_flutter: ^3.1.0
  animated_snack_bar: ^0.4.0
  carousel_slider: ^4.2.1
  badges: ^3.1.2
  flutter_localized_locales: ^2.0.5
  flutter_localization: ^0.2.0
  easy_localization: ^3.0.7
  dio: ^5.4.3+1
  shared_preferences: ^2.2.3
  material_floating_search_bar_2: ^0.5.0
  lottie: ^3.1.2
  flutter_svg: ^2.0.10+1
  rename: ^3.0.2
  flutter_phone_direct_caller: ^2.1.1
  country_picker: ^2.0.26
  # flutter_launcher_icons: ^0.13.1
  # google_maps_flutter: ^2.7.0
  intl_phone_number_input: ^0.7.4
  intl_phone_field: ^3.2.0
  flutter_image_compress: ^2.3.0
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.1
  flutter_facebook_auth: ^7.0.1
  video_player: ^2.9.1
  chewie: ^1.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icons/app_logo.png"

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    # - assets/lang/en.json
    - assets/lang/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: Wanderlust
      fonts:
        - asset: assets/fonts/Wanderlust.ttf
        
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
    - family: WILDWORLD
      fonts:
        - asset: assets/fonts/WILDWORLD.ttf

    - family: Modernist
      fonts:
        - asset: assets/fonts/Modernist-Regular.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
